FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

RUN apk add --no-cache \
      'postfix=3.11.7-r0' \
      'dovecot=2.4.5-r0' \
      'dovecot-lmtpd=2.4.5-r0' \
      'dovecot-pigeonhole-plugin=2.4.5-r0' \
      'opendkim=2.11.0-r4' \
      opendkim-utils \
      lmdb \
      ca-certificates \
      tzdata \
      supervisor \
      rsyslog \
      cronie \
    && sed -i 's/^module(load="imkmsg")/# Disabled in containers: no kernel log device./' /etc/rsyslog.conf \
    && addgroup -S -g 1001 mailstore \
    && adduser -S -D -H -u 1001 -h /var/email -s /sbin/nologin -G mailstore mailstore \
    && install -d -o dovecot -g dovecot /run/dovecot \
    && install -d -o opendkim -g opendkim /run/opendkim \
    && install -D -m 0644 /etc/postfix/postfix-files /usr/share/postfix/container/postfix-files \
    && install -D -m 0644 /etc/postfix/dynamicmaps.cf /usr/share/postfix/container/dynamicmaps.cf \
    && install -D -m 0644 /etc/postfix/dynamicmaps.cf.d/lmdb /usr/share/postfix/container/dynamicmaps.cf.d/lmdb \
    && rm -rf /var/cache/apk/*

COPY mailsystem/supervisord.conf /etc/supervisord.conf
COPY mailsystem/rsyslog-mail.conf /etc/rsyslog.d/10-mail-container.conf
COPY mailsystem/crontab /etc/crontabs/root
COPY mailsystem/startup.sh /usr/local/bin/startup.sh
COPY mailsystem/healthcheck.sh /usr/local/bin/healthcheck.sh

RUN chmod 0755 /usr/local/bin/startup.sh /usr/local/bin/healthcheck.sh

USER root
WORKDIR /tmp

EXPOSE 25 143 465 587 993

HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 \
  CMD ["/usr/local/bin/healthcheck.sh"]

ENTRYPOINT ["/usr/local/bin/startup.sh"]
